services:
  scheduler:
    build:
      context: /Users/porterlaartz/Desktop/School/Senior/CS 506/Project_11/scheduler
    restart: always
    depends_on:
      - database
      - api
    environment:
      COMPOSE_PROJECT_NAME: 'capitol_gains_prod'
      API_HOST: localhost
      API_PORT: 8000
      BUILD: 'production'
    ports:
      - '9000:9000'
