services:
  scheduler:
    build:
      context: ${BASE_DIR}/scheduler
    restart: always
    depends_on:
      - api
    environment:
      COMPOSE_PROJECT_NAME: 'Capitol_Gains'
      API_HOST: localhost
      API_PORT: 8000
      BUILD: 'production'
      STOCK_API_KEY: ${STOCK_API_KEY}
    ports:
      - '9000:9000'
    volumes:
      - scheduler_backup:/scheduler/backup
    networks:
      production_cg_network:

volumes:
  scheduler_backup:

networks:
  production_cg_network:
    external: true
