services:
  scheduler:
    build:
      context: ${BASE_DIR}/scheduler
    restart: always
    depends_on:
      - database
      - api
    environment:
      COMPOSE_PROJECT_NAME: 'capitol_gains_prod'
      API_HOST: localhost
      API_PORT: 8000
      BUILD: 'dev'
    ports:
      - '9000:9000'
    volumes:
      - $BASE_DIR/scheduler/scripts/python:/scheduler/scripts/python
