services:
  web:
    build:  
      context: ${BASE_DIR}/web
    restart: always
    depends_on:
      - database
      - api
    environment:
      BUILD: "production"
      COMPOSE_PROJECT_NAME: "Capitol_Gains_11"
      WEB_PORT: "443"
      API_PORT: "80"
      API_HOST: "localhost"
    ports:
      - '433:5173'
        