stages:
  - build
  - test

build-docker:
  stage: build
  tags:
    - csl
    - docker
  image: docker:latest
  services: 
    - name: docker:dind
  before_script:
    - docker info
  script:
    - docker compose build
    - |
      OUTPUT_FILE="docker_images.tar"
      docker save -o "$OUTPUT_FILE" \
        $(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E 'docker')
    - mv "$OUTPUT_FILE" "$CI_PROJECT_DIR/$OUTPUT_FILE"
  artifacts:
    paths:
      - docker_image.tar

unittest:
  stage: test
  tags:
    - csl
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker compose up -d
    - until docker compose exec api echo "API container is up"; do sleep 5; done
  script:
    - docker compose exec api python manage.py test
  artifacts:
    when: always
    untracked: true
    expire_in: 7 days
    paths:
      - api/unittest-results.log
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/