stages:
  - build
  - test

build-docker:
  stage: build
  tags:
    - csl
    - docker
  image: docker:latest
  services: 
    - name: docker:dind
  before_script:
    - docker info
  script:
    - docker-compose build -t app-image
  artifacts:
    paths:
      - docker_image.tar
  after_script:
    - docker save app-image > docker_image.tar

pytest:
  stage: test
  tags:
    - csl
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker-compose up -d
  script:
    - docker-compose exec api pytest --maxfail=1 --disable-warnings test/conftest.py
  artifacts:
    when: always
    untracked: true
    expire_in: 7 days
    paths:
      - api/pytest-results.log
  coverage: /TOTAL.+?(\d+%)/