stages:
  - build
  - test

build-docker:
  stage: build
  tags:
    - csl
    - docker
  image: docker:latest
  services: 
    - name: docker:dind
  before_script:
    - docker info
  script:
    - docker build -t app-image -f api/Dockerfile api/
  artifacts:
    paths:
      - docker_image.tar
  after_script:
    - docker save app-image > docker_image.tar

pytest:
  stage: test
  tags:
    - csl
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker-compose up --build -d
  script:
    - pytest --maxfail=1 --disable-warnings > $gitlab/pytest_results.log
  artifacts:
    when: always
    paths:
      - $gitlab/pytest_results.log
  coverage: /TOTAL.+?(\d+%)/