stages:
  - build
  - test

build-docker:
  stage: build
  tags:
    - csl
    - docker
  image: docker:latest
  services: 
    - name: docker:dind
  before_script:
    - docker info
  script:
    - docker compose build
    - |
      OUTPUT_FILE="docker_image.tar"
      
      TEMP_DIR=$(mktemp -d)

      for image in $(docker images --format "{{.Repository}}:{{.Tag}}"); do
          docker save -o "${TEMP_DIR}/${image//\//_}.tar" "$image"
      done

      tar -cf "$OUTPUT_FILE" -C "$TEMP_DIR" .
      
      rm -r "$TEMP_DIR"
    - mv docker_image.tar $CI_PROJECT_DIR/docker_image.tar
  artifacts:
    paths:
      - docker_image.tar

unittest:
  stage: test
  tags:
    - csl
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker compose up -d
    - until docker compose exec api echo "API container is up"; do sleep 5; done
  script:
    - docker compose exec api python -m unittest -v api/tests/test_fixtures.py
  artifacts:
    when: always
    untracked: true
    expire_in: 7 days
    paths:
      - api/unittest-results.log
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/