build-docker:
  stage: build
  tags:
    - csl
    - docker
  

pytest:
  stage: test
  tags:
    - csl
  image: python:3.9
  before_script:
    - docker compose up --build -d
  script:
    - pytest --maxfail=1 --disable-warnings
  artifacts:
    when: always
    paths:
      - pytest_results.log
  coverage: /TOTAL.+?(\d+%)/