services:
  database:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - dev_database:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
volumes:
  dev_database: