services:
  database:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: "production_db"
      MYSQL_ROOT_HOST: '%'
    volumes:
      - database:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
volumes:
  database: