# Generated by Django 5.1.1 on 2024-10-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_initial', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('description_short', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician_type', models.CharField(max_length=20)),
                ('politician_house', models.CharField(choices=[('R', 'Republican'), ('D', 'Democrat'), ('I', 'Independent')], max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.CharField(max_length=50)),
                ('transaction_date', models.DateField()),
                ('disclosure_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=10)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.politician')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stock')),
            ],
        ),
    ]
