FROM node:18-alpine AS builder

WORKDIR /web

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine AS production

COPY --from=builder /web/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
